server:
  port: 8082

spring:
  application:
    name: inventory-service
  
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  
  redis:
    host: redis
    port: 6379
  
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.eventdriven.inventory: DEBUG
    org.springframework.kafka: INFO 